package com.da.Photography.entity;
// Generated 2017-10-24 11:02:27 by Hibernate Tools 3.5.0.Final

import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaAlbums generated by hbm2java
 */
@Entity
@Table(name = "PA_ALBUMS", schema = "PHOTOGRAPHY")
public class PaAlbums implements java.io.Serializable {

	/**
	 * serialVersionUID = -1090744700894183093L
	 */
	private static final long serialVersionUID = -1090744700894183093L;
	private long AId;
	private PaUser paUser;
	private String AName;
	private Date ATime;
	private String AProfile;
	private Blob APic;
	private Set<PaPicture> paPictures = new HashSet<PaPicture>(0);

	public PaAlbums() {
	}

	public PaAlbums(long AId) {
		this.AId = AId;
	}

	public PaAlbums(long AId, PaUser paUser, String AName, Date ATime, String AProfile, Blob APic,
			Set<PaPicture> paPictures) {
		this.AId = AId;
		this.paUser = paUser;
		this.AName = AName;
		this.ATime = ATime;
		this.AProfile = AProfile;
		this.APic = APic;
		this.paPictures = paPictures;
	}

	@Id

	@Column(name = "A_ID", unique = true, nullable = false, precision = 11, scale = 0)
	public long getAId() {
		return this.AId;
	}

	public void setAId(long AId) {
		this.AId = AId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "U_ID")
	public PaUser getPaUser() {
		return this.paUser;
	}

	public void setPaUser(PaUser paUser) {
		this.paUser = paUser;
	}

	@Column(name = "A_NAME")
	public String getAName() {
		return this.AName;
	}

	public void setAName(String AName) {
		this.AName = AName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "A_TIME", length = 7)
	public Date getATime() {
		return this.ATime;
	}

	public void setATime(Date ATime) {
		this.ATime = ATime;
	}

	@Column(name = "A_PROFILE", length = 3000)
	public String getAProfile() {
		return this.AProfile;
	}

	public void setAProfile(String AProfile) {
		this.AProfile = AProfile;
	}

	@Column(name = "A_PIC")
	public Blob getAPic() {
		return this.APic;
	}

	public void setAPic(Blob APic) {
		this.APic = APic;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paAlbums")
	public Set<PaPicture> getPaPictures() {
		return this.paPictures;
	}

	public void setPaPictures(Set<PaPicture> paPictures) {
		this.paPictures = paPictures;
	}

}
