package com.da.Photography.entity;
// Generated 2017-10-24 11:02:27 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaDown generated by hbm2java
 */
@Entity
@Table(name = "PA_DOWN", schema = "PHOTOGRAPHY")
public class PaDown implements java.io.Serializable {

	/**
	 * serialVersionUID = 1928274020709293336L
	 */
	private static final long serialVersionUID = 1928274020709293336L;
	private long DId;
	private PaUser paUser;
	private Date DDate;
	private Short DType;
	private String DUpdate;
	private Long PId;

	public PaDown() {
	}

	public PaDown(long DId) {
		this.DId = DId;
	}

	public PaDown(long DId, PaUser paUser, Date DDate, Short DType, String DUpdate, Long PId) {
		this.DId = DId;
		this.paUser = paUser;
		this.DDate = DDate;
		this.DType = DType;
		this.DUpdate = DUpdate;
		this.PId = PId;
	}

	@Id

	@Column(name = "D_ID", unique = true, nullable = false, precision = 11, scale = 0)
	public long getDId() {
		return this.DId;
	}

	public void setDId(long DId) {
		this.DId = DId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "U_ID")
	public PaUser getPaUser() {
		return this.paUser;
	}

	public void setPaUser(PaUser paUser) {
		this.paUser = paUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "D_DATE", length = 7)
	public Date getDDate() {
		return this.DDate;
	}

	public void setDDate(Date DDate) {
		this.DDate = DDate;
	}

	@Column(name = "D_TYPE", precision = 4, scale = 0)
	public Short getDType() {
		return this.DType;
	}

	public void setDType(Short DType) {
		this.DType = DType;
	}

	@Column(name = "D_UPDATE", length = 10)
	public String getDUpdate() {
		return this.DUpdate;
	}

	public void setDUpdate(String DUpdate) {
		this.DUpdate = DUpdate;
	}

	@Column(name = "P_ID", precision = 11, scale = 0)
	public Long getPId() {
		return this.PId;
	}

	public void setPId(Long PId) {
		this.PId = PId;
	}

}
