package com.da.Photography.entity;
// Generated 2017-10-24 11:02:27 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PaUser generated by hbm2java
 */
@Entity
@Table(name = "PA_USER", schema = "PHOTOGRAPHY", uniqueConstraints = { @UniqueConstraint(columnNames = "U_UNAME"),
		@UniqueConstraint(columnNames = "U_EMAIL") })
public class PaUser implements java.io.Serializable {

	/**
	 * serialVersionUID = 3294342012338418723L
	 */
	private static final long serialVersionUID = 3294342012338418723L;
	private long UId;
	private String UName;
	private String UUname;
	private String UPwd;
	private String UPhone;
	private String UEmail;
	private Long UPrice;
	private BigDecimal UBalance;
	private Long USignday;
	private Date USigndate;
	private String URole;
	private Set<PaApplyadmin> paApplyadmins = new HashSet<PaApplyadmin>(0);
	private Set<PaAlbums> paAlbumses = new HashSet<PaAlbums>(0);
	private Set<PaDown> paDowns = new HashSet<PaDown>(0);

	public PaUser() {
	}

	public PaUser(long UId) {
		this.UId = UId;
	}

	public PaUser(long UId, String UName, String UUname, String UPwd, String UPhone, String UEmail, Long UPrice,
			BigDecimal UBalance, Long USignday, Date USigndate, String URole, Set<PaApplyadmin> paApplyadmins,
			Set<PaAlbums> paAlbumses, Set<PaDown> paDowns) {
		this.UId = UId;
		this.UName = UName;
		this.UUname = UUname;
		this.UPwd = UPwd;
		this.UPhone = UPhone;
		this.UEmail = UEmail;
		this.UPrice = UPrice;
		this.UBalance = UBalance;
		this.USignday = USignday;
		this.USigndate = USigndate;
		this.URole = URole;
		this.paApplyadmins = paApplyadmins;
		this.paAlbumses = paAlbumses;
		this.paDowns = paDowns;
	}

	@Id

	@Column(name = "U_ID", unique = true, nullable = false, precision = 11, scale = 0)
	public long getUId() {
		return this.UId;
	}

	public void setUId(long UId) {
		this.UId = UId;
	}

	@Column(name = "U_NAME")
	public String getUName() {
		return this.UName;
	}

	public void setUName(String UName) {
		this.UName = UName;
	}

	@Column(name = "U_UNAME", unique = true)
	public String getUUname() {
		return this.UUname;
	}

	public void setUUname(String UUname) {
		this.UUname = UUname;
	}

	@Column(name = "U_PWD")
	public String getUPwd() {
		return this.UPwd;
	}

	public void setUPwd(String UPwd) {
		this.UPwd = UPwd;
	}

	@Column(name = "U_PHONE", length = 50)
	public String getUPhone() {
		return this.UPhone;
	}

	public void setUPhone(String UPhone) {
		this.UPhone = UPhone;
	}

	@Column(name = "U_EMAIL", unique = true, length = 50)
	public String getUEmail() {
		return this.UEmail;
	}

	public void setUEmail(String UEmail) {
		this.UEmail = UEmail;
	}

	@Column(name = "U_PRICE", precision = 10, scale = 0)
	public Long getUPrice() {
		return this.UPrice;
	}

	public void setUPrice(Long UPrice) {
		this.UPrice = UPrice;
	}

	@Column(name = "U_BALANCE", precision = 20)
	public BigDecimal getUBalance() {
		return this.UBalance;
	}

	public void setUBalance(BigDecimal UBalance) {
		this.UBalance = UBalance;
	}

	@Column(name = "U_SIGNDAY", precision = 10, scale = 0)
	public Long getUSignday() {
		return this.USignday;
	}

	public void setUSignday(Long USignday) {
		this.USignday = USignday;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "U_SIGNDATE", length = 7)
	public Date getUSigndate() {
		return this.USigndate;
	}

	public void setUSigndate(Date USigndate) {
		this.USigndate = USigndate;
	}

	@Column(name = "U_ROLE", length = 2)
	public String getURole() {
		return this.URole;
	}

	public void setURole(String URole) {
		this.URole = URole;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paUser")
	public Set<PaApplyadmin> getPaApplyadmins() {
		return this.paApplyadmins;
	}

	public void setPaApplyadmins(Set<PaApplyadmin> paApplyadmins) {
		this.paApplyadmins = paApplyadmins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paUser")
	public Set<PaAlbums> getPaAlbumses() {
		return this.paAlbumses;
	}

	public void setPaAlbumses(Set<PaAlbums> paAlbumses) {
		this.paAlbumses = paAlbumses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paUser")
	public Set<PaDown> getPaDowns() {
		return this.paDowns;
	}

	public void setPaDowns(Set<PaDown> paDowns) {
		this.paDowns = paDowns;
	}

}
