package com.da.Photography.entity;
// Generated 2017-10-24 11:02:27 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PaApplyadmin generated by hbm2java
 */
@Entity
@Table(name = "PA_APPLYADMIN", schema = "PHOTOGRAPHY")
public class PaApplyadmin implements java.io.Serializable {

	/**
	 * serialVersionUID = -3105808289944440201L
	 */
	private static final long serialVersionUID = -3105808289944440201L;
	private long adId;
	private PaUser paUser;

	public PaApplyadmin() {
	}

	public PaApplyadmin(long adId, PaUser paUser) {
		this.adId = adId;
		this.paUser = paUser;
	}

	@Id

	@Column(name = "AD_ID", nullable = false, precision = 11, scale = 0)
	public long getAdId() {
		return this.adId;
	}

	public void setAdId(long adId) {
		this.adId = adId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "U_ID", nullable = false)
	public PaUser getPaUser() {
		return this.paUser;
	}

	public void setPaUser(PaUser paUser) {
		this.paUser = paUser;
	}

}
