package com.da.Photography.entity;
// Generated 2017-10-24 11:02:27 by Hibernate Tools 3.5.0.Final

import java.sql.Blob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaPicture generated by hbm2java
 */
@Entity
@Table(name = "PA_PICTURE", schema = "PHOTOGRAPHY")
public class PaPicture implements java.io.Serializable {

	/**
	 * serialVersionUID = 8497235816178673190L
	 */
	private static final long serialVersionUID = 8497235816178673190L;
	private long PId;
	private PaAlbums paAlbums;
	private String PName;
	private Date PTime;
	private Blob PPic;
	private Long PPrice;
	private String PProfile;

	public PaPicture() {
	}

	public PaPicture(long PId) {
		this.PId = PId;
	}

	public PaPicture(long PId, PaAlbums paAlbums, String PName, Date PTime, Blob PPic, Long PPrice, String PProfile) {
		this.PId = PId;
		this.paAlbums = paAlbums;
		this.PName = PName;
		this.PTime = PTime;
		this.PPic = PPic;
		this.PPrice = PPrice;
		this.PProfile = PProfile;
	}

	@Id

	@Column(name = "P_ID", unique = true, nullable = false, precision = 11, scale = 0)
	public long getPId() {
		return this.PId;
	}

	public void setPId(long PId) {
		this.PId = PId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "A_ID")
	public PaAlbums getPaAlbums() {
		return this.paAlbums;
	}

	public void setPaAlbums(PaAlbums paAlbums) {
		this.paAlbums = paAlbums;
	}

	@Column(name = "P_NAME")
	public String getPName() {
		return this.PName;
	}

	public void setPName(String PName) {
		this.PName = PName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "P_TIME", length = 7)
	public Date getPTime() {
		return this.PTime;
	}

	public void setPTime(Date PTime) {
		this.PTime = PTime;
	}

	@Column(name = "P_PIC")
	public Blob getPPic() {
		return this.PPic;
	}

	public void setPPic(Blob PPic) {
		this.PPic = PPic;
	}

	@Column(name = "P_PRICE", precision = 10, scale = 0)
	public Long getPPrice() {
		return this.PPrice;
	}

	public void setPPrice(Long PPrice) {
		this.PPrice = PPrice;
	}

	@Column(name = "P_PROFILE", length = 3000)
	public String getPProfile() {
		return this.PProfile;
	}

	public void setPProfile(String PProfile) {
		this.PProfile = PProfile;
	}

}
